#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


Color_Off='\033[0m'
BYellow='\033[1;33m'  

# Prettier
echo -e "\n${BYellow} === Code Formatter Process Started === ${Color_Off}"
npm run prettier

# Linting
echo -e "\n${BYellow} === Linting Process Started === ${Color_Off}"
npm run lint